project:
  type: default

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    css:
      - styles/mobile.css
    html-math-method: mathjax

  pdf:
    include-in-header:
      - tex/preamble.tex
    pdf-engine: lualatex
    toc: true
    number-sections: true
    keep-tex: false
    mainfont: "TeX Gyre Termes"
    CJKmainfont: "Noto Serif CJK JP"
